import PDFDocument from 'pdfkit';
import type { Response } from 'express';
import fs from 'fs';
import { ContractBillingFrequency, ContractPricingType, ContractSignatureStatus, ContractStatus } from '@prisma/client';
import { resolveCompanyAssetUrl } from '@modules/settings/companyAssetUpload';

type ContractPdf = {
  contractNumber: string;
  title: string;
  status: ContractStatus;
  language: string;
  startDate: Date | null;
  endDate: Date | null;
  amount: unknown;
  currency: string;
  pricingType?: ContractPricingType;
  unitRate?: unknown;
  fixedAmount?: unknown;
  billingFrequency?: ContractBillingFrequency;
  taxRate?: unknown;
  paymentTermsDays?: number | null;
  billingDescription?: string | null;
  summary: string | null;
  terms: string | null;
  pdfHash: string | null;
  client: {
    name: string;
    email: string;
    company: string | null;
    address?: string | null;
    city?: string | null;
    country?: string | null;
    taxNumber?: string | null;
  };
  createdBy: { name: string; email: string };
  signedVersion?: { versionNumber: number; contentHash: string } | null;
  companySignedBy?: { name: string; email: string } | null;
  currentVersion?: {
    versionNumber: number;
    content: string;
    contentHash: string;
    signatureStatus?: ContractSignatureStatus;
    companySignatureUrl?: string | null;
    companyStampUrl?: string | null;
    companySignedAt?: Date | null;
    clientSignerName?: string | null;
    clientSignerEmail?: string | null;
    clientSignedAt?: Date | null;
    signedPdfHash?: string | null;
    revokedAt?: Date | null;
    revocationReason?: string | null;
  } | null;
};

type CompanySettings = {
  name: string;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  taxNumber?: string | null;
  signatureUrl?: string | null;
  stampUrl?: string | null;
};

const labels = {
  fr: {
    title: 'Contrat',
    client: 'Client',
    company: 'Entreprise',
    dates: 'Dates',
    start: 'Debut',
    end: 'Fin',
    amount: 'Montant',
    status: 'Statut',
    version: 'Version',
    hash: 'Empreinte',
    generated: 'Genere le',
    generatedBy: 'Genere par',
    signature: 'Signature de la societe',
    stamp: 'Cachet de la societe',
    clientSignature: 'Signature du client',
    signedBy: 'Signe par',
    signedAt: 'Date de signature',
    revoked: 'SIGNATURE REVOQUEE',
    revocationReason: 'Motif de revocation',
    pricing: 'Tarification',
    pricingType: 'Modele',
    billingFrequency: 'Frequence',
    taxRate: 'TVA',
    paymentTerms: 'Paiement',
    fixedAmount: 'Forfait',
    unitRate: 'Tarif',
  },
  en: {
    title: 'Contract',
    client: 'Client',
    company: 'Company',
    dates: 'Dates',
    start: 'Start',
    end: 'End',
    amount: 'Amount',
    status: 'Status',
    version: 'Version',
    hash: 'Hash',
    generated: 'Generated on',
    generatedBy: 'Generated by',
    signature: 'Company signature',
    stamp: 'Company stamp',
    clientSignature: 'Client signature',
    signedBy: 'Signed by',
    signedAt: 'Signed on',
    revoked: 'SIGNATURE REVOKED',
    revocationReason: 'Revocation reason',
    pricing: 'Pricing',
    pricingType: 'Model',
    billingFrequency: 'Frequency',
    taxRate: 'Tax',
    paymentTerms: 'Payment',
    fixedAmount: 'Fixed',
    unitRate: 'Rate',
  },
  ar: {
    title: '\u0639\u0642\u062f',
    client: '\u0627\u0644\u0639\u0645\u064a\u0644',
    company: '\u0627\u0644\u0634\u0631\u0643\u0629',
    dates: '\u0627\u0644\u062a\u0648\u0627\u0631\u064a\u062e',
    start: '\u0627\u0644\u0628\u062f\u0627\u064a\u0629',
    end: '\u0627\u0644\u0646\u0647\u0627\u064a\u0629',
    amount: '\u0627\u0644\u0645\u0628\u0644\u063a',
    status: '\u0627\u0644\u062d\u0627\u0644\u0629',
    version: '\u0627\u0644\u0625\u0635\u062f\u0627\u0631',
    hash: '\u0627\u0644\u0628\u0635\u0645\u0629',
    generated: '\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u0625\u0646\u0634\u0627\u0621',
    generatedBy: '\u0623\u0646\u0634\u0626 \u0628\u0648\u0627\u0633\u0637\u0629',
    signature: '\u062a\u0648\u0642\u064a\u0639 \u0627\u0644\u0634\u0631\u0643\u0629',
    stamp: '\u062e\u062a\u0645 \u0627\u0644\u0634\u0631\u0643\u0629',
    clientSignature: '\u062a\u0648\u0642\u064a\u0639 \u0627\u0644\u0639\u0645\u064a\u0644',
    signedBy: '\u0648\u0642\u0639\u0647',
    signedAt: '\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0648\u0642\u064a\u0639',
    revoked: '\u0627\u0644\u062a\u0648\u0642\u064a\u0639 \u0645\u0644\u063a\u0649',
    revocationReason: '\u0633\u0628\u0628 \u0627\u0644\u0625\u0644\u063a\u0627\u0621',
    pricing: '\u0627\u0644\u062a\u0633\u0639\u064a\u0631',
    pricingType: '\u0627\u0644\u0646\u0645\u0648\u0630\u062c',
    billingFrequency: '\u0627\u0644\u0648\u062a\u064a\u0631\u0629',
    taxRate: '\u0627\u0644\u0636\u0631\u064a\u0628\u0629',
    paymentTerms: '\u0627\u0644\u062f\u0641\u0639',
    fixedAmount: '\u0627\u0644\u0645\u0628\u0644\u063a \u0627\u0644\u062b\u0627\u0628\u062a',
    unitRate: '\u0627\u0644\u062a\u0639\u0631\u064a\u0641\u0629',
  },
} as const;

type ContractPdfLabels = (typeof labels)[keyof typeof labels];

export function renderContractPdf(contract: ContractPdf, company: CompanySettings, res: Response) {
  const doc = new PDFDocument({ size: 'A4', margin: 42, bufferPages: true });
  doc.pipe(res);
  drawContract(doc, contract, company, contract.language);
  doc.end();
}

export async function renderContractPdfBuffer(contract: ContractPdf, company: CompanySettings, language = 'fr'): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 42, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));
  drawContract(doc, contract, company, language);
  doc.end();
  return done;
}

function drawContract(doc: PDFKit.PDFDocument, contract: ContractPdf, company: CompanySettings, language: string) {
  const t = labels[language.startsWith('ar') ? 'ar' : language.startsWith('en') ? 'en' : 'fr'];
  const rtl = language.startsWith('ar');
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const left = doc.page.margins.left;
  doc.info.Title = `${t.title} ${contract.contractNumber}`;

  doc.rect(0, 0, doc.page.width, 90).fill('#111827');
  doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text(t.title, left, 30, { width, align: rtl ? 'right' : 'left' });
  doc.fontSize(12).font('Helvetica').text(contract.contractNumber, left, 58, { width, align: rtl ? 'right' : 'left' });

  doc.fillColor('#111827').fontSize(16).font('Helvetica-Bold').text(contract.title, left, 118, { width, align: rtl ? 'right' : 'left' });
  drawBadge(doc, left + width - 120, 116, statusLabel(contract.status), statusColor(contract.status));

  const top = 152;
  drawBox(doc, left, top, width / 2 - 8, 95, t.company, [
    company.name,
    company.email,
    company.phone,
    company.address,
    company.taxNumber,
  ], rtl);
  drawBox(doc, left + width / 2 + 8, top, width / 2 - 8, 95, t.client, [
    contract.client.company ?? contract.client.name,
    contract.client.name,
    contract.client.email,
    contract.client.address,
    contract.client.city,
    contract.client.country,
    contract.client.taxNumber,
  ], rtl);

  const metaTop = 262;
  drawMeta(doc, left, metaTop, width, [
    [t.start, formatDate(contract.startDate)],
    [t.end, formatDate(contract.endDate)],
    [t.amount, contract.amount == null ? '-' : formatMoney(Number(contract.amount), contract.currency)],
    [t.version, String(contract.currentVersion?.versionNumber ?? '-')],
  ], rtl);

  drawPricing(doc, contract, left, metaTop + 66, width, rtl, t);

  doc.y = metaTop + 136;
  const content = contract.currentVersion?.content ?? contract.terms ?? contract.summary ?? '';
  doc.fillColor('#111827').font('Helvetica').fontSize(10.5);
  doc.text(content, left, doc.y, {
    width,
    align: rtl ? 'right' : 'left',
    lineGap: 4,
    height: 180,
    ellipsis: true,
  });

  drawSignatureBlock(doc, contract, left, 585, width, rtl, t);

  const footerTop = 710;
  doc.moveTo(left, footerTop).lineTo(left + width, footerTop).strokeColor('#e5e7eb').stroke();
  doc.fillColor('#64748b').fontSize(8);
  doc.text(`${t.hash}: ${contract.pdfHash ?? contract.currentVersion?.contentHash ?? '-'}`, left, footerTop + 12, { width, align: rtl ? 'right' : 'left' });
  doc.text(`${t.generated}: ${formatDateTime(new Date())}`, left, footerTop + 26, { width: width / 2 });
  doc.text(`${t.generatedBy}: ${contract.createdBy.name}`, left + width / 2, footerTop + 26, { width: width / 2, align: 'right' });
  doc.text('1 / 1', left, 770, { width, align: 'center' });
}

function drawSignatureBlock(
  doc: PDFKit.PDFDocument,
  contract: ContractPdf,
  left: number,
  top: number,
  width: number,
  rtl: boolean,
  t: ContractPdfLabels
) {
  const version = contract.currentVersion;
  const hasCompanySignature = Boolean(version?.companySignedAt && version.companySignatureUrl);
  const hasClientSignature = Boolean(version?.clientSignedAt && version.clientSignerName);
  const isRevoked = version?.signatureStatus === ContractSignatureStatus.REVOKED || Boolean(version?.revokedAt);
  if (!hasCompanySignature && !hasClientSignature && !isRevoked) return;

  doc.roundedRect(left, top, width, 110, 8).fillAndStroke(isRevoked ? '#fff1f2' : '#f0fdf4', isRevoked ? '#fecdd3' : '#bbf7d0');
  if (isRevoked) {
    doc.fillColor('#be123c').font('Helvetica-Bold').fontSize(13).text(t.revoked, left + 14, top + 12, { width: width - 28, align: rtl ? 'right' : 'left' });
    doc.fillColor('#9f1239').font('Helvetica').fontSize(8.5).text(`${t.revocationReason}: ${version?.revocationReason ?? '-'}`, left + 14, top + 30, { width: width - 28, align: rtl ? 'right' : 'left', ellipsis: true });
  }

  const columnWidth = (width - 52) / 2;
  const signatureX = rtl ? left + width - columnWidth - 14 : left + 14;
  const stampX = rtl ? left + 14 : left + columnWidth + 38;
  const imageTop = top + 48;

  doc.fillColor('#065f46').font('Helvetica-Bold').fontSize(8.5);
  doc.text(t.signature, signatureX, imageTop - 18, { width: columnWidth, align: 'center' });
  doc.text(t.stamp, stampX, imageTop - 18, { width: columnWidth, align: 'center' });

  drawPdfImageIfPresent(doc, resolveCompanyAssetUrl(version?.companySignatureUrl), signatureX, imageTop, columnWidth, 34);
  drawPdfImageIfPresent(doc, resolveCompanyAssetUrl(version?.companyStampUrl), stampX, imageTop - 4, columnWidth, 42);

  doc.fillColor('#047857').font('Helvetica').fontSize(7.5);
  const signer = contract.companySignedBy?.name ?? '-';
  doc.text(`${t.signedBy}: ${signer}`, signatureX, top + 86, { width: columnWidth, align: 'center', ellipsis: true });
  if (version?.companySignedAt) {
    doc.text(`${t.signedAt}: ${formatDateTime(version.companySignedAt)}`, stampX, top + 86, { width: columnWidth, align: 'center', ellipsis: true });
  }
  if (hasClientSignature) {
    doc.fillColor('#0f172a').font('Helvetica-Bold').fontSize(7.5).text(`${t.clientSignature}: ${version?.clientSignerName ?? '-'}`, left + 14, top + 100, { width: width - 28, align: rtl ? 'right' : 'left', ellipsis: true });
  }
}

function drawPdfImageIfPresent(doc: PDFKit.PDFDocument, imagePath: string | null, x: number, y: number, width: number, height: number) {
  if (!imagePath || !fs.existsSync(imagePath)) return;
  const dimensions = readImageDimensions(imagePath);
  if (!dimensions || dimensions.width < 24 || dimensions.height < 16) return;
  doc.image(imagePath, x, y, { fit: [width, height], align: 'center', valign: 'center' });
}

function readImageDimensions(imagePath: string) {
  const buffer = fs.readFileSync(imagePath);
  if (buffer.length >= 24 && buffer.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
    return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
  }

  if (buffer.length > 4 && buffer[0] === 0xff && buffer[1] === 0xd8) {
    let offset = 2;
    while (offset + 9 < buffer.length) {
      if (buffer[offset] !== 0xff) break;
      const marker = buffer[offset + 1];
      if (typeof marker !== 'number') break;
      const length = buffer.readUInt16BE(offset + 2);
      if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
        return { width: buffer.readUInt16BE(offset + 7), height: buffer.readUInt16BE(offset + 5) };
      }
      offset += 2 + length;
    }
  }

  return null;
}

function drawBox(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, title: string, lines: Array<string | null | undefined>, rtl: boolean) {
  doc.roundedRect(x, y, w, h, 8).fillAndStroke('#f8fafc', '#e2e8f0');
  doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text(title.toUpperCase(), x + 12, y + 12, { width: w - 24, align: rtl ? 'right' : 'left' });
  doc.fillColor('#111827').font('Helvetica').fontSize(9);
  doc.text(lines.filter(Boolean).join('\n'), x + 12, y + 30, { width: w - 24, height: h - 36, align: rtl ? 'right' : 'left', ellipsis: true });
}

function drawMeta(doc: PDFKit.PDFDocument, x: number, y: number, w: number, items: string[][], rtl: boolean) {
  const itemWidth = w / items.length;
  items.forEach((item, index) => {
    const label = item[0] ?? '';
    const value = item[1] ?? '';
    const itemX = x + index * itemWidth;
    doc.roundedRect(itemX + 4, y, itemWidth - 8, 54, 8).fillAndStroke('#ffffff', '#e2e8f0');
    doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text(label.toUpperCase(), itemX + 14, y + 10, { width: itemWidth - 28, align: rtl ? 'right' : 'left' });
    doc.fillColor('#0f172a').fontSize(11).text(value, itemX + 14, y + 28, { width: itemWidth - 28, align: rtl ? 'right' : 'left' });
  });
}

function drawPricing(
  doc: PDFKit.PDFDocument,
  contract: ContractPdf,
  x: number,
  y: number,
  w: number,
  rtl: boolean,
  t: ContractPdfLabels
) {
  doc.roundedRect(x + 4, y, w - 8, 58, 8).fillAndStroke('#f8fafc', '#e2e8f0');
  doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text(t.pricing.toUpperCase(), x + 16, y + 10, { width: w - 32, align: rtl ? 'right' : 'left' });
  const items = [
    [t.pricingType, formatEnum(contract.pricingType ?? ContractPricingType.FIXED)],
    [t.billingFrequency, formatEnum(contract.billingFrequency ?? ContractBillingFrequency.ONE_TIME)],
    [t.fixedAmount, contract.fixedAmount == null ? '-' : formatMoney(Number(contract.fixedAmount), contract.currency)],
    [t.unitRate, contract.unitRate == null ? '-' : formatMoney(Number(contract.unitRate), contract.currency)],
    [t.taxRate, `${Number(contract.taxRate ?? 0)}%`],
    [t.paymentTerms, `${contract.paymentTermsDays ?? 30} j`],
  ];
  const itemWidth = (w - 32) / items.length;
  items.forEach((item, index) => {
    const itemX = x + 16 + index * itemWidth;
    doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(6.8).text(item[0] ?? '', itemX, y + 28, { width: itemWidth - 6, align: rtl ? 'right' : 'left' });
    doc.fillColor('#0f172a').font('Helvetica').fontSize(7.8).text(item[1] ?? '', itemX, y + 40, { width: itemWidth - 6, align: rtl ? 'right' : 'left', ellipsis: true });
  });
}

function drawBadge(doc: PDFKit.PDFDocument, x: number, y: number, label: string, color: string) {
  doc.roundedRect(x, y, 120, 24, 12).fill(color);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(8).text(label, x, y + 8, { width: 120, align: 'center' });
}

function statusLabel(status: ContractStatus) {
  return status.replace(/_/g, ' ');
}

function statusColor(status: ContractStatus) {
  const colors: Record<ContractStatus, string> = {
    DRAFT: '#64748b',
    SENT: '#2563eb',
    VIEWED: '#7c3aed',
    SIGNED: '#059669',
    ACTIVE: '#16a34a',
    EXPIRED: '#f97316',
    TERMINATED: '#dc2626',
    CANCELLED: '#94a3b8',
  };
  return colors[status];
}

function formatDate(value: Date | null) {
  return value ? new Intl.DateTimeFormat('fr-FR').format(value) : '-';
}

function formatDateTime(value: Date) {
  return new Intl.DateTimeFormat('fr-FR', { dateStyle: 'short', timeStyle: 'short' }).format(value);
}

function formatMoney(value: number, currency: string) {
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency }).format(value);
}

function formatEnum(value: string) {
  return value.toLowerCase().replace(/_/g, ' ');
}
