import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { CompanySettings, ExpenseNoteStatus } from '@prisma/client';
import { resolveReceiptStorageKey } from './expense.upload';

type PdfLanguage = 'en' | 'fr' | 'ar';

type ExpensePdfNote = {
  id: string;
  status: ExpenseNoteStatus;
  expenseDate: Date;
  amountTTC: unknown;
  amountHT?: unknown | null;
  vatAmount: unknown;
  vatRate: unknown;
  comment?: string | null;
  merchantName?: string | null;
  receiptNumber?: string | null;
  documentNumber?: string | null;
  currency: string;
  source: string;
  aiConfidence?: unknown | null;
  createdAt: Date;
  submittedAt?: Date | null;
  approvedAt?: Date | null;
  rejectedAt?: Date | null;
  paidAt?: Date | null;
  category?: { name: string } | null;
  expenseType?: { name: string } | null;
  createdBy?: { name: string; email: string } | null;
  approvedBy?: { name: string; email: string } | null;
  rejectedBy?: { name: string; email: string } | null;
  paidBy?: { name: string; email: string } | null;
  attachments?: Array<{
    originalName: string;
    mimeType: string;
    storageKey: string;
  }>;
  auditLogs?: Array<{
    action: string;
    createdAt: Date;
    actor?: { name: string; email: string } | null;
  }>;
};

const labels = {
  fr: {
    title: 'NOTE DE FRAIS',
    company: 'Entreprise',
    employee: 'Employe',
    details: 'Details de la depense',
    amount: 'Montants',
    audit: 'Resume audit',
    receipt: 'Justificatif',
    generatedBy: 'Genere par',
    generatedAt: 'Date de generation',
    page: 'Page',
    merchant: 'Marchand',
    documentNumber: 'Numero de recu',
    category: 'Categorie',
    type: 'Type de frais',
    date: 'Date',
    status: 'Statut',
    source: 'Source',
    amountHT: 'Montant HT',
    vatRate: 'TVA',
    vatAmount: 'Montant TVA',
    amountTTC: 'Montant TTC',
    currency: 'Devise',
    approvedBy: 'Approuve par',
    approvedAt: 'Date approbation',
    comment: 'Commentaire',
    noReceipt: 'Aucun justificatif joint.',
    pdfReceipt: 'Justificatif PDF joint au dossier.',
  },
  en: {
    title: 'EXPENSE NOTE',
    company: 'Company',
    employee: 'Employee',
    details: 'Expense details',
    amount: 'Amounts',
    audit: 'Audit summary',
    receipt: 'Receipt',
    generatedBy: 'Generated by',
    generatedAt: 'Generated at',
    page: 'Page',
    merchant: 'Merchant',
    documentNumber: 'Receipt number',
    category: 'Category',
    type: 'Expense type',
    date: 'Date',
    status: 'Status',
    source: 'Source',
    amountHT: 'Amount excl. VAT',
    vatRate: 'VAT',
    vatAmount: 'VAT amount',
    amountTTC: 'Amount incl. VAT',
    currency: 'Currency',
    approvedBy: 'Approved by',
    approvedAt: 'Approval date',
    comment: 'Comment',
    noReceipt: 'No receipt attached.',
    pdfReceipt: 'PDF receipt attached to the expense note.',
  },
  ar: {
    title: 'EXPENSE NOTE',
    company: 'Company',
    employee: 'Employee',
    details: 'Expense details',
    amount: 'Amounts',
    audit: 'Audit summary',
    receipt: 'Receipt',
    generatedBy: 'Generated by',
    generatedAt: 'Generated at',
    page: 'Page',
    merchant: 'Merchant',
    documentNumber: 'Receipt number',
    category: 'Category',
    type: 'Expense type',
    date: 'Date',
    status: 'Status',
    source: 'Source',
    amountHT: 'Amount excl. VAT',
    vatRate: 'VAT',
    vatAmount: 'VAT amount',
    amountTTC: 'Amount incl. VAT',
    currency: 'Currency',
    approvedBy: 'Approved by',
    approvedAt: 'Approval date',
    comment: 'Comment',
    noReceipt: 'No receipt attached.',
    pdfReceipt: 'PDF receipt attached to the expense note.',
  },
} satisfies Record<PdfLanguage, Record<string, string>>;

type ExpensePdfLabels = typeof labels.fr;

export function renderExpensePdf(
  note: ExpensePdfNote,
  company: CompanySettings,
  generatedBy: { name: string; email: string },
  output: NodeJS.WritableStream,
  language: PdfLanguage = 'fr'
) {
  const doc = new PDFDocument({ bufferPages: true, compress: false, margin: 34, size: 'A4' });
  doc.pipe(output);
  drawExpensePdf(doc, note, company, generatedBy, language);
  doc.end();
}

export function renderExpensePdfBuffer(
  note: ExpensePdfNote,
  company: CompanySettings,
  generatedBy: { name: string; email: string },
  language: PdfLanguage = 'fr'
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ bufferPages: true, compress: false, margin: 34, size: 'A4' });
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    drawExpensePdf(doc, note, company, generatedBy, language);
    doc.end();
  });
}

export function renderExpenseReportPdfBuffer(
  notes: ExpensePdfNote[],
  company: CompanySettings,
  generatedBy: { name: string; email: string },
  language: PdfLanguage = 'fr'
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ bufferPages: true, compress: false, margin: 42, size: 'A4' });
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const t: ExpensePdfLabels = labels[language] ?? labels.fr;
    doc.info.Title = 'Expense Notes Report';
    doc.info.Author = company.name;
    doc.rect(0, 0, doc.page.width, 92).fill('#0f172a');
    doc.font('Helvetica-Bold').fontSize(22).fillColor('#ffffff').text('EXPENSE NOTES REPORT', pageLeft(doc), 32, {
      width: pageWidth(doc),
    });
    doc.font('Helvetica').fontSize(8.5).fillColor('#cbd5e1').text(company.name, pageLeft(doc), 62);
    doc.y = 116;

    const totalHT = notes.reduce((sum, note) => sum + Number(note.amountHT ?? 0), 0);
    const totalVat = notes.reduce((sum, note) => sum + Number(note.vatAmount), 0);
    const totalTTC = notes.reduce((sum, note) => sum + Number(note.amountTTC), 0);
    drawCard(doc, pageLeft(doc), doc.y, pageWidth(doc), 72, '#f8fafc', '#e2e8f0');
    drawMeta(doc, pageLeft(doc) + 16, doc.y + 14, 'COUNT', String(notes.length));
    drawMeta(doc, pageLeft(doc) + 150, doc.y + 14, t.amountHT, formatCurrency(totalHT, notes[0]?.currency ?? 'MAD'));
    drawMeta(doc, pageLeft(doc) + 286, doc.y + 14, t.vatAmount, formatCurrency(totalVat, notes[0]?.currency ?? 'MAD'));
    drawMeta(doc, pageLeft(doc) + 422, doc.y + 14, t.amountTTC, formatCurrency(totalTTC, notes[0]?.currency ?? 'MAD'), true);
    doc.y += 92;

    const columns = [
      { label: t.employee, width: 105, align: 'left' as const },
      { label: t.merchant, width: 120, align: 'left' as const },
      { label: t.date, width: 70, align: 'left' as const },
      { label: t.category, width: 105, align: 'left' as const },
      { label: t.amountTTC, width: 78, align: 'right' as const },
      { label: t.status, width: 62, align: 'left' as const },
    ];
    drawReportTableHeader(doc, columns);
    notes.forEach((note, index) => drawReportRow(doc, columns, [
      note.createdBy?.name ?? '-',
      note.merchantName ?? '-',
      formatDate(note.expenseDate),
      `${note.category?.name ?? '-'} / ${note.expenseType?.name ?? '-'}`,
      formatCurrency(Number(note.amountTTC), note.currency),
      note.status,
    ], index));

    drawFooters(doc, company, generatedBy, t);
    doc.end();
  });
}

function drawExpensePdf(
  doc: PDFKit.PDFDocument,
  note: ExpensePdfNote,
  company: CompanySettings,
  generatedBy: { name: string; email: string },
  language: PdfLanguage
) {
  const t: ExpensePdfLabels = labels[language] ?? labels.fr;
  doc.info.Title = `${t.title} ${expenseReference(note)}`;
  doc.info.Author = company.name;

  drawCompactHeader(doc, note, company, t);
  drawCompactParties(doc, note, company, t);
  drawCompactDetails(doc, note, t);
  drawCompactAuditAndReceipt(doc, note, t);
  drawFooters(doc, company, generatedBy, t);
}

function drawCompactHeader(doc: PDFKit.PDFDocument, note: ExpensePdfNote, company: CompanySettings, t: ExpensePdfLabels) {
  const left = pageLeft(doc);
  const width = pageWidth(doc);
  doc.rect(0, 0, doc.page.width, 82).fill('#0f172a');
  doc.rect(0, 64, doc.page.width, 18).fill('#2563eb');
  doc.roundedRect(left, 23, 34, 34, 8).fill('#ffffff');
  doc.font('Helvetica-Bold').fontSize(13).fillColor('#2563eb');
  doc.text(initials(company.name), left, 34, { width: 34, align: 'center' });
  doc.font('Helvetica-Bold').fontSize(14).fillColor('#ffffff');
  doc.text(company.name, left + 46, 22, { width: 250, ellipsis: true });
  doc.font('Helvetica').fontSize(7.5).fillColor('#cbd5e1');
  doc.text([company.address, company.phone, company.email].filter(Boolean).join(' | '), left + 46, 42, {
    width: 285,
    ellipsis: true,
  });
  doc.font('Helvetica-Bold').fontSize(20).fillColor('#ffffff');
  doc.text(t.title, left + width - 210, 22, { width: 210, align: 'right' });
  doc.font('Helvetica-Bold').fontSize(9).fillColor('#bfdbfe');
  doc.text(expenseReference(note), left + width - 210, 47, { width: 210, align: 'right' });
  drawBadge(doc, left + width - 118, 64, 118, 17, note.status, statusColor(note.status));
  doc.y = 96;
}

function drawCompactParties(doc: PDFKit.PDFDocument, note: ExpensePdfNote, company: CompanySettings, t: ExpensePdfLabels) {
  const left = pageLeft(doc);
  const gap = 10;
  const cardWidth = (pageWidth(doc) - gap) / 2;
  const top = doc.y;
  drawInfoCard(doc, left, top, cardWidth, 66, t.company, [
    company.name,
    company.email,
    company.phone,
    company.taxNumber,
  ]);
  drawInfoCard(doc, left + cardWidth + gap, top, cardWidth, 66, t.employee, [
    note.createdBy?.name,
    note.createdBy?.email,
  ]);
  doc.y = top + 76;
}

function drawCompactDetails(doc: PDFKit.PDFDocument, note: ExpensePdfNote, t: ExpensePdfLabels) {
  const left = pageLeft(doc);
  const width = pageWidth(doc);
  doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#0f172a');
  doc.text(t.details, left, doc.y, { width });
  doc.y += 14;

  const top = doc.y;
  drawCard(doc, left, top, width, 82, '#ffffff', '#dbeafe');
  const rows: Array<[string, string]> = [
    [t.merchant, note.merchantName ?? '-'],
    [t.documentNumber, note.documentNumber ?? note.receiptNumber ?? '-'],
    [t.category, note.category?.name ?? '-'],
    [t.type, note.expenseType?.name ?? '-'],
    [t.date, formatDate(note.expenseDate)],
    [t.source, note.source],
  ];
  rows.forEach((row, index) => drawCompactMeta(doc, left + 14 + (index % 3) * 176, top + 12 + Math.floor(index / 3) * 32, row[0], row[1]));
  doc.y = top + 94;

  doc.font('Helvetica-Bold').fontSize(10.5).fillColor('#0f172a');
  doc.text(t.amount, left, doc.y, { width });
  doc.y += 14;
  const amountTop = doc.y;
  drawCard(doc, left, amountTop, width, 58, '#f8fafc', '#e2e8f0');
  drawCompactMeta(doc, left + 14, amountTop + 12, t.amountHT, formatCurrency(Number(note.amountHT ?? 0), note.currency));
  drawCompactMeta(doc, left + 146, amountTop + 12, t.vatRate, `${Number(note.vatRate).toFixed(2)}%`);
  drawCompactMeta(doc, left + 278, amountTop + 12, t.vatAmount, formatCurrency(Number(note.vatAmount), note.currency));
  drawCompactMeta(doc, left + 410, amountTop + 12, t.amountTTC, formatCurrency(Number(note.amountTTC), note.currency), true);
  doc.y = amountTop + 70;

  if (note.approvedBy || note.approvedAt || note.comment) {
    const approvalTop = doc.y;
    drawCard(doc, left, approvalTop, width, 50, '#ecfdf5', '#bbf7d0');
    drawCompactMeta(doc, left + 14, approvalTop + 10, t.approvedBy, note.approvedBy?.name ?? '-');
    drawCompactMeta(doc, left + 176, approvalTop + 10, t.approvedAt, note.approvedAt ? formatDateTime(note.approvedAt) : '-');
    drawCompactMeta(doc, left + 338, approvalTop + 10, t.comment, trimText(note.comment ?? '-', 52));
    doc.y = approvalTop + 60;
  }
}

function drawCompactAuditAndReceipt(doc: PDFKit.PDFDocument, note: ExpensePdfNote, t: ExpensePdfLabels) {
  const left = pageLeft(doc);
  const width = pageWidth(doc);
  const gap = 10;
  const auditWidth = Math.round(width * 0.48);
  const receiptWidth = width - auditWidth - gap;
  const top = doc.y;
  const blockHeight = 176;

  drawCard(doc, left, top, auditWidth, blockHeight, '#ffffff', '#e2e8f0');
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#0f172a').text(t.audit, left + 12, top + 10, { width: auditWidth - 24 });
  const logs = (note.auditLogs ?? []).slice(-3);
  if (logs.length) {
    logs.forEach((log, index) => {
      const y = top + 34 + index * 42;
      doc.circle(left + 16, y + 6, 3).fill(statusColor(log.action).foreground);
      doc.font('Helvetica-Bold').fontSize(7.8).fillColor('#0f172a').text(trimText(log.action, 24), left + 26, y, {
        width: auditWidth - 38,
        ellipsis: true,
      });
      doc.font('Helvetica').fontSize(7.2).fillColor('#64748b').text(`${log.actor?.name ?? '-'} - ${formatDateTime(log.createdAt)}`, left + 26, y + 12, {
        width: auditWidth - 38,
        ellipsis: true,
      });
    });
  } else {
    doc.font('Helvetica').fontSize(8).fillColor('#64748b').text('-', left + 12, top + 34, { width: auditWidth - 24 });
  }

  const receiptLeft = left + auditWidth + gap;
  drawCard(doc, receiptLeft, top, receiptWidth, blockHeight, '#ffffff', '#e2e8f0');
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#0f172a').text(t.receipt, receiptLeft + 12, top + 10, { width: receiptWidth - 24 });
  const attachment = note.attachments?.[0];
  if (!attachment) {
    doc.font('Helvetica').fontSize(8).fillColor('#64748b').text(t.noReceipt, receiptLeft + 12, top + 34, { width: receiptWidth - 24 });
  } else {
    const filePath = resolveReceiptStorageKey(attachment.storageKey);
    if (attachment.mimeType.startsWith('image/') && fs.existsSync(filePath)) {
      doc.image(filePath, receiptLeft + 12, top + 32, {
        fit: [receiptWidth - 24, 122],
        align: 'center',
        valign: 'center',
      });
    } else {
      doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#334155').text(t.pdfReceipt, receiptLeft + 12, top + 36, { width: receiptWidth - 24 });
      doc.font('Helvetica').fontSize(7.5).fillColor('#64748b').text(trimText(path.basename(attachment.originalName), 52), receiptLeft + 12, top + 54, { width: receiptWidth - 24 });
    }
  }
  doc.y = top + blockHeight + 8;
}

function drawHeader(doc: PDFKit.PDFDocument, note: ExpensePdfNote, company: CompanySettings, t: ExpensePdfLabels) {
  const left = pageLeft(doc);
  const width = pageWidth(doc);
  doc.rect(0, 0, doc.page.width, 104).fill('#0f172a');
  doc.rect(0, 78, doc.page.width, 26).fill('#2563eb');
  doc.roundedRect(left, 30, 44, 44, 10).fill('#ffffff');
  doc.font('Helvetica-Bold').fontSize(16).fillColor('#2563eb');
  doc.text(initials(company.name), left, 43, { width: 44, align: 'center' });
  doc.font('Helvetica-Bold').fontSize(17).fillColor('#ffffff');
  doc.text(company.name, left + 58, 30, { width: 265, ellipsis: true });
  doc.font('Helvetica').fontSize(8.5).fillColor('#cbd5e1');
  doc.text([company.address, company.phone, company.email].filter(Boolean).join(' | '), left + 58, 55, {
    width: 280,
    lineGap: 1,
  });
  doc.font('Helvetica-Bold').fontSize(24).fillColor('#ffffff');
  doc.text(t.title, left + width - 220, 30, { width: 220, align: 'right' });
  doc.font('Helvetica-Bold').fontSize(11).fillColor('#bfdbfe');
  doc.text(expenseReference(note), left + width - 220, 60, { width: 220, align: 'right' });
  drawBadge(doc, left + width - 132, 79, 132, 20, note.status, statusColor(note.status));
  doc.y = 124;
}

function drawParties(doc: PDFKit.PDFDocument, note: ExpensePdfNote, company: CompanySettings, t: ExpensePdfLabels) {
  const left = pageLeft(doc);
  const gap = 14;
  const cardWidth = (pageWidth(doc) - gap) / 2;
  const top = doc.y;
  drawInfoCard(doc, left, top, cardWidth, 92, t.company, [
    company.name,
    company.email,
    company.phone,
    company.taxNumber,
  ]);
  drawInfoCard(doc, left + cardWidth + gap, top, cardWidth, 92, t.employee, [
    note.createdBy?.name,
    note.createdBy?.email,
  ]);
  doc.y = top + 108;
}

function drawDetails(doc: PDFKit.PDFDocument, note: ExpensePdfNote, t: ExpensePdfLabels) {
  ensureSpace(doc, 180);
  const left = pageLeft(doc);
  const width = pageWidth(doc);
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#0f172a');
  doc.text(t.details, left, doc.y, { width });
  doc.y += 18;
  const top = doc.y;
  drawCard(doc, left, top, width, 116, '#ffffff', '#dbeafe');
  const rows: Array<[string, string]> = [
    [t.merchant, note.merchantName ?? '-'],
    [t.documentNumber, note.documentNumber ?? note.receiptNumber ?? '-'],
    [t.category, note.category?.name ?? '-'],
    [t.type, note.expenseType?.name ?? '-'],
    [t.date, formatDate(note.expenseDate)],
    [t.source, note.source],
  ];
  rows.forEach((row, index) => drawMeta(doc, left + 16 + (index % 2) * 258, top + 14 + Math.floor(index / 2) * 31, row[0], row[1]));
  doc.y = top + 132;

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#0f172a');
  doc.text(t.amount, left, doc.y, { width });
  doc.y += 18;
  const amountTop = doc.y;
  drawCard(doc, left, amountTop, width, 78, '#f8fafc', '#e2e8f0');
  drawMeta(doc, left + 16, amountTop + 14, t.amountHT, formatCurrency(Number(note.amountHT ?? 0), note.currency));
  drawMeta(doc, left + 148, amountTop + 14, t.vatRate, `${Number(note.vatRate).toFixed(2)}%`);
  drawMeta(doc, left + 280, amountTop + 14, t.vatAmount, formatCurrency(Number(note.vatAmount), note.currency));
  drawMeta(doc, left + 412, amountTop + 14, t.amountTTC, formatCurrency(Number(note.amountTTC), note.currency), true);
  doc.y = amountTop + 94;

  if (note.approvedBy || note.approvedAt || note.comment) {
    const approvalTop = doc.y;
    drawCard(doc, left, approvalTop, width, 70, '#ecfdf5', '#bbf7d0');
    drawMeta(doc, left + 16, approvalTop + 12, t.approvedBy, note.approvedBy?.name ?? '-');
    drawMeta(doc, left + 190, approvalTop + 12, t.approvedAt, note.approvedAt ? formatDateTime(note.approvedAt) : '-');
    drawMeta(doc, left + 360, approvalTop + 12, t.comment, note.comment ?? '-');
    doc.y = approvalTop + 86;
  }
}

function drawAudit(doc: PDFKit.PDFDocument, note: ExpensePdfNote, t: ExpensePdfLabels) {
  const logs = (note.auditLogs ?? []).slice(-6);
  if (!logs.length) return;
  ensureSpace(doc, 46 + logs.length * 22);
  const left = pageLeft(doc);
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#0f172a');
  doc.text(t.audit, left, doc.y, { width: pageWidth(doc) });
  doc.y += 16;
  logs.forEach((log) => {
    ensureSpace(doc, 24);
    doc.circle(left + 5, doc.y + 6, 3).fill(statusColor(log.action).foreground);
    doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#0f172a');
    doc.text(log.action, left + 16, doc.y, { width: 165, lineBreak: false });
    doc.font('Helvetica').fillColor('#64748b');
    doc.text(`${log.actor?.name ?? '-'} - ${formatDateTime(log.createdAt)}`, left + 184, doc.y, {
      width: pageWidth(doc) - 184,
      lineBreak: false,
    });
    doc.y += 20;
  });
  doc.y += 4;
}

function drawReceipt(doc: PDFKit.PDFDocument, note: ExpensePdfNote, t: ExpensePdfLabels) {
  const attachment = note.attachments?.[0];
  ensureSpace(doc, 170);
  const left = pageLeft(doc);
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#0f172a');
  doc.text(t.receipt, left, doc.y, { width: pageWidth(doc) });
  doc.y += 18;
  const top = doc.y;
  drawCard(doc, left, top, pageWidth(doc), 150, '#ffffff', '#e2e8f0');
  if (!attachment) {
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text(t.noReceipt, left + 16, top + 18);
    doc.y = top + 166;
    return;
  }
  const filePath = resolveReceiptStorageKey(attachment.storageKey);
  if (attachment.mimeType.startsWith('image/') && fs.existsSync(filePath)) {
    doc.image(filePath, left + 16, top + 14, { fit: [pageWidth(doc) - 32, 118], align: 'center', valign: 'center' });
  } else {
    const fileName = path.basename(attachment.originalName);
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#334155').text(t.pdfReceipt, left + 16, top + 18);
    doc.font('Helvetica').fontSize(9).fillColor('#64748b').text(fileName, left + 16, top + 38);
  }
  doc.y = top + 166;
}

function drawInfoCard(doc: PDFKit.PDFDocument, x: number, y: number, width: number, height: number, title: string, lines: Array<string | null | undefined>) {
  drawCard(doc, x, y, width, height, '#ffffff', '#dbeafe');
  doc.font('Helvetica-Bold').fontSize(8).fillColor('#2563eb').text(title.toUpperCase(), x + 14, y + 14);
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#0f172a');
  const clean = lines.filter((line): line is string => Boolean(line));
  doc.text(clean[0] ?? '-', x + 14, y + 34, { width: width - 28, ellipsis: true });
  doc.font('Helvetica').fontSize(8.5).fillColor('#475569');
  clean.slice(1).forEach((line, index) => doc.text(line, x + 14, y + 50 + index * 12, { width: width - 28, ellipsis: true }));
}

function drawMeta(doc: PDFKit.PDFDocument, x: number, y: number, label: string, value: string, strong = false) {
  doc.font('Helvetica-Bold').fontSize(7.2).fillColor('#64748b').text(label.toUpperCase(), x, y, { width: 120 });
  doc.font('Helvetica-Bold').fontSize(strong ? 11 : 9.5).fillColor(strong ? '#0f172a' : '#334155').text(value, x, y + 13, {
    width: 118,
    ellipsis: true,
  });
}

function drawCompactMeta(doc: PDFKit.PDFDocument, x: number, y: number, label: string, value: string, strong = false) {
  doc.font('Helvetica-Bold').fontSize(6.8).fillColor('#64748b').text(label.toUpperCase(), x, y, { width: 122 });
  doc.font('Helvetica-Bold').fontSize(strong ? 9.2 : 8.2).fillColor(strong ? '#0f172a' : '#334155').text(value, x, y + 11, {
    width: 120,
    ellipsis: true,
  });
}

function drawBadge(doc: PDFKit.PDFDocument, x: number, y: number, width: number, height: number, label: string, colors: { background: string; foreground: string }) {
  doc.roundedRect(x, y, width, height, height / 2).fill(colors.background);
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor(colors.foreground);
  doc.text(label, x + 8, y + 7, { width: width - 16, align: 'center' });
}

function drawCard(doc: PDFKit.PDFDocument, x: number, y: number, width: number, height: number, fill: string, stroke: string) {
  doc.roundedRect(x, y, width, height, 8).fill(fill);
  doc.strokeColor(stroke).lineWidth(0.8).roundedRect(x, y, width, height, 8).stroke();
}

function drawReportTableHeader(doc: PDFKit.PDFDocument, columns: Array<{ label: string; width: number; align: 'left' | 'right' }>) {
  ensureSpace(doc, 34);
  const left = pageLeft(doc);
  doc.roundedRect(left, doc.y, pageWidth(doc), 24, 6).fill('#2563eb');
  doc.font('Helvetica-Bold').fontSize(7.5).fillColor('#ffffff');
  let x = left;
  columns.forEach((column) => {
    doc.text(column.label, x + 6, doc.y + 8, { width: column.width - 12, align: column.align });
    x += column.width;
  });
  doc.y += 28;
}

function drawReportRow(doc: PDFKit.PDFDocument, columns: Array<{ width: number; align: 'left' | 'right' }>, cells: string[], index: number) {
  ensureSpace(doc, 34);
  const left = pageLeft(doc);
  const top = doc.y;
  doc.roundedRect(left, top, pageWidth(doc), 28, 4).fill(index % 2 === 0 ? '#ffffff' : '#f8fafc');
  doc.strokeColor('#e2e8f0').lineWidth(0.4).roundedRect(left, top, pageWidth(doc), 28, 4).stroke();
  doc.font('Helvetica').fontSize(7.5).fillColor('#334155');
  let x = left;
  cells.forEach((cell, cellIndex) => {
    const column = columns[cellIndex];
    if (!column) return;
    doc.text(cell, x + 6, top + 9, { width: column.width - 12, align: column.align, ellipsis: true });
    x += column.width;
  });
  doc.y += 30;
}

function drawFooters(doc: PDFKit.PDFDocument, company: CompanySettings, generatedBy: { name: string; email: string }, t: ExpensePdfLabels) {
  const range = doc.bufferedPageRange();
  for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
    doc.switchToPage(pageIndex);
    const left = pageLeft(doc);
    const y = doc.page.height - doc.page.margins.bottom - 18;
    doc.moveTo(left, y - 10).lineTo(pageRight(doc), y - 10).strokeColor('#e2e8f0').lineWidth(0.6).stroke();
    doc.font('Helvetica').fontSize(7).fillColor('#64748b');
    doc.text(`${t.generatedBy}: ${generatedBy.name} | ${t.generatedAt}: ${formatDateTime(new Date())}`, left, y, { width: 360 });
    doc.text(`${t.page} ${pageIndex - range.start + 1} / ${range.count}`, pageRight(doc) - 90, y, { width: 90, align: 'right' });
    doc.text(company.email ?? company.name, left, y + 10, { width: 280 });
  }
}

function ensureSpace(doc: PDFKit.PDFDocument, requiredHeight: number) {
  if (doc.y + requiredHeight <= doc.page.height - doc.page.margins.bottom - 28) return;
  doc.addPage();
  doc.y = 54;
}

function pageLeft(doc: PDFKit.PDFDocument) {
  return doc.page.margins.left;
}

function pageRight(doc: PDFKit.PDFDocument) {
  return doc.page.width - doc.page.margins.right;
}

function pageWidth(doc: PDFKit.PDFDocument) {
  return pageRight(doc) - pageLeft(doc);
}

function initials(name: string) {
  return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join('');
}

function expenseReference(note: ExpensePdfNote) {
  return note.documentNumber || note.receiptNumber || `EXP-${note.id.slice(0, 8).toUpperCase()}`;
}

function statusColor(status: string) {
  const colors: Record<string, { background: string; foreground: string }> = {
    DRAFT: { background: '#f1f5f9', foreground: '#334155' },
    PROCESSING: { background: '#e0f2fe', foreground: '#0369a1' },
    NEEDS_REVIEW: { background: '#fef3c7', foreground: '#b45309' },
    SUBMITTED: { background: '#dbeafe', foreground: '#1d4ed8' },
    CHANGES_REQUESTED: { background: '#ffedd5', foreground: '#c2410c' },
    APPROVED: { background: '#dcfce7', foreground: '#15803d' },
    REJECTED: { background: '#fee2e2', foreground: '#b91c1c' },
    PAID: { background: '#ede9fe', foreground: '#6d28d9' },
  };
  return colors[status] ?? { background: '#f1f5f9', foreground: '#334155' };
}

function formatCurrency(amount: number, currency: string) {
  return new Intl.NumberFormat('fr-MA', { style: 'currency', currency, minimumFractionDigits: 2 }).format(amount);
}

function formatDate(date: Date) {
  return new Intl.DateTimeFormat('fr-MA', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
}

function formatDateTime(date: Date) {
  return new Intl.DateTimeFormat('fr-MA', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(date);
}

function trimText(value: string, length: number) {
  return value.length > length ? `${value.slice(0, Math.max(0, length - 1))}.` : value;
}
